### ISSUE TITLE
QEMU launch NodeOS failed

### ISSUE THREAD

**Issue by joeking11829** [NodeOS/NodeOS#92]
Hi,
I'm new to NodeOS.
I'm trying to build NodeOS.

use npm install to get and build NodeOS

But, when i use qemu-system-x86_64 to launch NodeOS

When linux kernel initial, it stay on :

.........................
[   20.437522] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   20.524758] ip_tables: (C) 2000-2006 Netfilter Core Team
[   20.652660] TCP: cubic registered
[   20.751746] Initializing XFRM netlink socket
[   20.815748] NET: Registered protocol family 10
[   20.884425]  sda: unknown partition table
[   21.045296] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   21.092952] sd 0:0:0:0: [sda] Attached SCSI disk
[   21.133849] sit: IPv6 over IPv4 tunneling driver
[   21.184698] NET: Registered protocol family 17
[   21.232982] Key type dns_resolver registered
[   21.351737] registered taskstats version 1
[   21.422624]   Magic number: 15:958:761
[   21.446296] console [netcon0] enabled
[   21.476595] netconsole: network logging started
[   21.642662] ALSA device list:
[   21.653663]   No soundcards found.
[   22.132709] Freeing unused kernel memory: 5948K (ffffffff81a72000 - ffffffff82041000)
[   22.216699] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3

It can not launch successfully !!
What can i do !?

**Comment by piranna** [comment]
It should work out of the box. Could you be able to start only the
barebones layer and check the output?

**Comment by joeking11829** [comment]
Hi piranna,

I do "npm start" at node-barebones

it look like same prolem.

...................................
[   22.994589] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   23.023719] sit: IPv6 over IPv4 tunneling driver
[   23.074669] NET: Registered protocol family 17
[   23.104734] Key type dns_resolver registered
[   23.230797] registered taskstats version 1
[   23.454525]   Magic number: 15:388:671
[   23.474530] console [netcon0] enabled
[   23.488452] netconsole: network logging started
[   23.516814] ALSA device list:
[   23.537326]   No soundcards found.
[   23.594545] ata2.00: configured for MWDMA2
[   23.799704] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3
[   23.861341] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.0. PQ: 0 ANSI: 5
[   24.016374] sr 1:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[   24.042542] cdrom: Uniform CD-ROM driver Revision: 3.20
[   24.096758] sr 1:0:0:0: Attached scsi generic sg0 type 5
[   24.512716] Freeing unused kernel memory: 5948K (ffffffff81a72000 - ffffffff82041000)


I launch it on my Ubuntu VM.
Is that a problem !?

**Comment by piranna** [comment]
It's really strange what you say... pleasy try with 'PLATFORM=qemu_32 npm
install', if this doesn't work then maybe the VM is giving problems... Also
give me the output of 'uname -a'.

By the way, the timestamp are too high, they should be just 2 seconds, not
20.

**Comment by joeking11829** [comment]
I am trying to do "PLATFORM=qemu_32 npm install".

And my result of "uname -a" is:

Linux APPLE 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by piranna** [comment]
> And my result of "uname -a" is:
>
> Linux APPLE 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014
x86_64 x86_64 x86_64 GNU/Linux

It's really strange, it should work... Could you give me the full outputs?
Or there's nothing after that?

**Comment by joeking11829** [comment]
Same problem on qemu-system-i386

qemu-system-i386 -enable-kvm -nographic --kernel bzImage -append console=ttyS0

full log outputs:
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.18.3 (root@APPLE) (gcc version 4.7.3 (GCC) ) #1 SMP Thu Jan 22 15:24:05 CST 2015
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000007ffdfff] usable
[    0.000000] BIOS-e820: [mem 0x0000000007ffe000-0x0000000007ffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] Notice: NX (Execute Disable) protection missing in CPU!
[    0.000000] SMBIOS 2.4 present.
[    0.000000] e820: last_pfn = 0x7ffe max_arch_pfn = 0x100000
[    0.000000] found SMP MP-table at [mem 0x000f0b70-0x000f0b7f] mapped at [c00f0b70]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] init_memory_mapping: [mem 0x00000000-0x000fffff]
[    0.000000] init_memory_mapping: [mem 0x07800000-0x07bfffff]
[    0.000000] init_memory_mapping: [mem 0x00100000-0x077fffff]
[    0.000000] init_memory_mapping: [mem 0x07c00000-0x07ffdfff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x000F09E0 000014 (v00 BOCHS )
[    0.000000] ACPI: RSDT 0x07FFFBC1 000034 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACP 0x07FFF1C0 000074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 0x07FFE040 001180 (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACS 0x07FFE000 000040
[    0.000000] ACPI: SSDT 0x07FFF234 0008DD (v01 BOCHS  BXPCSSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: APIC 0x07FFFB11 000078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[    0.000000] ACPI: HPET 0x07FFFB89 000038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[    0.000000] 0MB HIGHMEM available.
[    0.000000] 127MB LOWMEM available.
[    0.000000]   mapped low ram: 0 - 07ffe000
[    0.000000]   low ram: 0 - 07ffe000
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x00001000-0x00ffffff]
[    0.000000]   Normal   [mem 0x01000000-0x07ffdfff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00001000-0x0009efff]
[    0.000000]   node   0: [mem 0x00100000-0x07ffdfff]
[    0.000000] Initmem setup node 0 [mem 0x00001000-0x07ffdfff]
[    0.000000] Using APIC driver default
[    0.000000] ACPI: PM-Timer IO Port: 0xb008
[    0.000000] ACPI: LAPIC (acpi_id[0x00] lapic_id[0x00] enabled)
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[    0.000000] ACPI: IOAPIC (id[0x00] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x8086a201 base: 0xfed00000
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
[    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000effff]
[    0.000000] PM: Registered nosave memory: [mem 0x000f0000-0x000fffff]
[    0.000000] e820: [mem 0x08000000-0xfeffbfff] available for PCI devices
[    0.000000] setup_percpu: NR_CPUS:8 nr_cpumask_bits:8 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 12 pages/cpu @c7eef000 s27136 r0 d22016 u49152
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32412
[    0.000000] Kernel command line: console=ttyS0
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Initializing CPU#0
[    0.000000] Initializing HighMem for node 0 (00000000:00000000)
[    0.000000] Memory: 113896K/130672K available (7129K kernel code, 354K rwdata, 2008K rodata, 5416K init, 508K bss, 16776K reserved, 0K highmem)
[    0.000000] virtual kernel memory layout:
[    0.000000]     fixmap  : 0xfff16000 - 0xfffff000   ( 932 kB)
[    0.000000]     pkmap   : 0xff800000 - 0xffc00000   (4096 kB)
[    0.000000]     vmalloc : 0xc87fe000 - 0xff7fe000   ( 880 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xc7ffe000   ( 127 MB)
[    0.000000]       .init : 0xc1948000 - 0xc1e92000   (5416 kB)
[    0.000000]       .data : 0xc16f699e - 0xc1946b40   (2368 kB)
[    0.000000]       .text : 0xc1000000 - 0xc16f699e   (7130 kB)
[    0.000000] Checking if this processor honours the WP bit even in supervisor mode...Ok.
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS:2304 nr_irqs:256 0
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [ttyS0] enabled
[    0.000000] tsc: Fast TSC calibration failed
[    0.000000] tsc: Unable to calibrate against PIT
[    0.000000] tsc: HPET/PMTIMER calibration failed
[    0.000000] tsc: Marking TSC unstable due to could not calculate TSC khz
[    0.012000] Calibrating delay loop... 2297.85 BogoMIPS (lpj=1148928)
[    0.026000] pid_max: default: 32768 minimum: 301
[    0.027000] ACPI: Core revision 20140926
[    0.029000] ACPI: All ACPI Tables successfully acquired
[    0.035000] Security Framework initialized
[    0.036000] SELinux:  Initializing.
[    0.037000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.038000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.039000] Initializing cgroup subsys freezer
[    0.045000] Last level iTLB entries: 4KB 0, 2MB 0, 4MB 0
[    0.045000] Last level dTLB entries: 4KB 0, 2MB 0, 4MB 0, 1GB 0
[    0.811000] Freeing SMP alternatives memory: 28K (c1e92000 - c1e99000)
[    0.814000] Enabling APIC mode:  Flat.  Using 1 I/O APICs
[    0.918000] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.923000] smpboot: CPU0: Intel QEMU Virtual CPU version 2.0.0 (fam: 06, model: 06, stepping: 03)
[    0.929000] Performance Events: Broken PMU hardware detected, using software events only.
[    0.931000] Failed to access perfctr msr (MSR c1 is 0)
[    0.932000] x86: Booted up 1 node, 1 CPUs
[    0.934000] smpboot: Total of 1 processors activated (2297.85 BogoMIPS)
[    0.949000] devtmpfs: initialized
[    0.953000] RTC time:  7:28:43, date: 01/22/15
[    0.954000] NET: Registered protocol family 16
[    0.955000] cpuidle: using governor ladder
[    0.956000] cpuidle: using governor menu
[    0.957000] ACPI: bus type PCI registered
[    0.962000] PCI: PCI BIOS revision 2.10 entry at 0xfd3c2, last bus=0
[    0.964000] PCI: Using configuration type 1 for base access
[    0.969000] ACPI: Added _OSI(Module Device)
[    0.970000] ACPI: Added _OSI(Processor Device)
[    0.972000] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.973000] ACPI: Added _OSI(Processor Aggregator Device)
[    0.985000] ACPI: Interpreter enabled
[    0.986000] ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S1_] (20140926/hwxface-580)
[    0.989000] ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S2_] (20140926/hwxface-580)
[    0.992000] ACPI: (supports S0 S3 S4 S5)
[    0.994000] ACPI: Using IOAPIC for interrupt routing
[    0.995000] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    1.003000] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    1.005000] acpi PNP0A03:00: _OSC: OS supports [ASPM ClockPM Segments MSI]
[    1.006000] acpi PNP0A03:00: _OSC failed (AE_NOT_FOUND); disabling ASPM
[    1.008000] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[    1.009000] PCI host bridge to bus 0000:00
[    1.010000] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.011000] pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7]
[    1.012000] pci_bus 0000:00: root bus resource [io  0x0d00-0xadff]
[    1.013000] pci_bus 0000:00: root bus resource [io  0xae0f-0xaeff]
[    1.014000] pci_bus 0000:00: root bus resource [io  0xaf20-0xafdf]
[    1.015000] pci_bus 0000:00: root bus resource [io  0xafe4-0xffff]
[    1.016000] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff]
[    1.017000] pci_bus 0000:00: root bus resource [mem 0x08000000-0xfebfffff]
[    1.066000] pci 0000:00:01.1: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[    1.067000] pci 0000:00:01.1: legacy IDE quirk: reg 0x14: [io  0x03f6]
[    1.068000] pci 0000:00:01.1: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[    1.069000] pci 0000:00:01.1: legacy IDE quirk: reg 0x1c: [io  0x0376]
[    1.089000] pci 0000:00:01.3: quirk: [io  0xb000-0xb03f] claimed by PIIX4 ACPI
[    1.091000] pci 0000:00:01.3: quirk: [io  0xb100-0xb10f] claimed by PIIX4 SMB
[    1.171000] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[    1.179000] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[    1.188000] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[    1.196000] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[    1.203000] ACPI: PCI Interrupt Link [LNKS] (IRQs *9)
[    1.207000] ACPI: Enabled 16 GPEs in block 00 to 0F
[    1.208000] vgaarb: setting as boot device: PCI:0000:00:02.0
[    1.208000] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    1.209000] vgaarb: loaded
[    1.211000] vgaarb: bridge control possible 0000:00:02.0
[    1.212000] SCSI subsystem initialized
[    1.213000] ACPI: bus type USB registered
[    1.215000] usbcore: registered new interface driver usbfs
[    1.216000] usbcore: registered new interface driver hub
[    1.217000] usbcore: registered new device driver usb
[    1.218000] pps_core: LinuxPPS API ver. 1 registered
[    1.219000] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    1.220000] PTP clock support registered
[    1.221000] Advanced Linux Sound Architecture Driver Initialized.
[    1.222000] PCI: Using ACPI for IRQ routing
[    1.226000] NetLabel: Initializing
[    1.227000] NetLabel:  domain hash size = 128
[    1.228000] NetLabel:  protocols = UNLABELED CIPSOv4
[    1.230000] cfg80211: Calling CRDA to update world regulatory domain
[    1.232000] NetLabel:  unlabeled traffic allowed by default
[    1.234000] HPET: 3 timers in total, 0 timers will be used for per-cpu timer
[    1.235000] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0
[    1.240000] hpet0: 3 comparators, 64-bit 100.000000 MHz counter
[    1.245544] Switched to clocksource hpet
[    1.291623] pnp: PnP ACPI init
[    1.461697] pnp: PnP ACPI: found 6 devices
[    1.525684] hrtimer: interrupt took 3176610 ns
[    1.633563] NET: Registered protocol family 2
[    1.665585] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    1.734618] TCP bind hash table entries: 1024 (order: 1, 8192 bytes)
[    1.755297] TCP: Hash tables configured (established 1024 bind 1024)
[    1.843561] TCP: reno registered
[    1.854778] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    1.873707] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    1.918573] NET: Registered protocol family 1
[    1.957589] RPC: Registered named UNIX socket transport module.
[    1.977668] RPC: Registered udp transport module.
[    1.993498] RPC: Registered tcp transport module.
[    2.011548] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    2.074574] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    2.097557] pci 0000:00:01.0: PIIX3: Enabling Passive Release
[    2.120677] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    3.856687] microcode: CPU0 sig=0x663, pf=0x1, revision=0x1
[    3.911591] microcode: Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
[    3.985623] Scanning for low memory corruption every 60 seconds
[    4.054595] futex hash table entries: 256 (order: 2, 16384 bytes)
[    4.115554] audit: initializing netlink subsys (disabled)
[    4.158591] audit: type=2000 audit(1421911724.158:1): initialized
[    4.261657] HugeTLB registered 4 MB page size, pre-allocated 0 pages
[    4.384623] VFS: Disk quotas dquot_6.5.2
[    4.423638] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    4.482672] NFS: Registering the id_resolver key type
[    4.533678] Key type id_resolver registered
[    4.574583] Key type id_legacy registered
[    4.613627] fuse init (API version 7.23)
[    4.663547] msgmni has been set to 222
[    4.785606] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    4.856667] io scheduler noop registered
[    4.885667] io scheduler deadline registered
[    4.932596] io scheduler cfq registered (default)
[    4.981608] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    5.030637] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    5.093605] ACPI: Power Button [PWRF]
[    5.165595] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    5.263689] serial 00:05: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    5.387633] Non-volatile memory driver v1.3
[    5.431590] Linux agpgart interface v0.103
[    5.485686] [drm] Initialized drm 1.1.0 20060810
[    5.670612] loop: module loaded
[    5.781615] scsi host0: ata_piix
[    5.864659] scsi host1: ata_piix
[    5.892593] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc040 irq 14
[    5.915747] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc048 irq 15
[    6.027602] e100: Intel(R) PRO/100 Network Driver, 3.5.24-k2-NAPI
[    6.047423] e100: Copyright(c) 1999-2006 Intel Corporation
[    6.069542] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    6.092737] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    6.121925] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 11
[   22.337568] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 52:54:00:12:34:56
[   22.374558] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[   22.404904] e1000e: Intel(R) PRO/1000 Network Driver - 2.3.2-k
[   22.425789] e1000e: Copyright(c) 1999 - 2014 Intel Corporation.
[   22.470572] sky2: driver version 1.30
[   22.575587] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   22.599521] ehci-pci: EHCI PCI platform driver
[   22.615291] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[   22.636371] ohci-pci: OHCI PCI platform driver
[   22.663597] uhci_hcd: USB Universal Host Controller Interface driver
[   22.709621] usbcore: registered new interface driver usblp
[   22.739579] usbcore: registered new interface driver usb-storage
[   22.777717] i8042: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[   22.889356] serio: i8042 KBD port at 0x60,0x64 irq 1
[   22.907670] serio: i8042 AUX port at 0x60,0x64 irq 12
[   22.951563] mousedev: PS/2 mouse device common for all mice
[   23.017608] rtc_cmos 00:00: RTC can wake from S4
[   23.052769] rtc_cmos 00:00: rtc core: registered rtc_cmos as rtc0
[   23.089773] rtc_cmos 00:00: alarms up to one day, 114 bytes nvram, hpet irqs
[   23.118647] hpet1: lost 1 rtc interrupts
[   23.217591] device-mapper: ioctl: 4.28.0-ioctl (2014-09-17) initialised: dm-devel@redhat.com
[   23.261671] hidraw: raw HID events driver (C) Jiri Kosina
[   23.328633] usbcore: registered new interface driver usbhid
[   23.347818] usbhid: USB HID core driver
[   23.423648] Netfilter messages via NETLINK v0.30.
[   23.451605] nf_conntrack version 0.5.0 (1780 buckets, 7120 max)
[   23.525648] ctnetlink v0.93: registering with nfnetlink.
[   23.607559] ip_tables: (C) 2000-2006 Netfilter Core Team
[   23.659584] TCP: cubic registered
[   23.670743] Initializing XFRM netlink socket
[   23.725605] NET: Registered protocol family 10
[   23.802575] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   23.823551] sit: IPv6 over IPv4 tunneling driver
[   23.878597] NET: Registered protocol family 17
[   23.910589] Key type dns_resolver registered
[   23.925553] mce: Unable to init device /dev/mcelog (rc: -5)
[   23.985645] Using IPI No-Shortcut mode
[   24.040652] registered taskstats version 1
[   24.099593]   Magic number: 15:288:471
[   24.122596] console [netcon0] enabled
[   24.135481] netconsole: network logging started
[   24.154560] ALSA device list:
[   24.165560]   No soundcards found.
[   24.215605] ata2.00: ATAPI: QEMU DVD-ROM, 2.0.0, max UDMA/100
[   24.275824] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[   24.526717] ata2.00: configured for MWDMA2
[   24.562653] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.0. PQ: 0 ANSI: 5
[   24.646780] sr 1:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[   24.670574] cdrom: Uniform CD-ROM driver Revision: 3.20
[   24.729641] sr 1:0:0:0: Attached scsi generic sg0 type 5
[   25.018544] Freeing unused kernel memory: 5416K (c1948000 - c1e92000)
[   26.011618] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3

...........there's nothing after this

**Comment by piranna** [comment]
> Same problem on qemu-system-i386
>
> qemu-system-i386 -enable-kvm -nographic --kernel bzImage -append console=ttyS0

Then honestly I don't know what could be happening here, sorry :-/
Only last posibility is about you are compiling it on an Ubuntu VM
instead of a native install, but that should not be a problem. Please
upgrade your Ubuntu VM and all its related software and try again. If
this doesn't work, try again with a native install. If this doesn't
work, well... :-/

For reference, I'm using as development platform Ubuntu Mate 14.10
both on a Dell Latitude 500 (Core2 Duo, but using a 32 bits system)
and now on a MacBook Pro 2012 pre-Retina (i5 quad core, 64 bits
system, and the reason of the work on the cross-compiler)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by netlovers** [comment]
Inside a VM I had to remove the `-enable-kvm` part, although if I remember correctly it gave me a useful error message.

**Comment by piranna** [comment]
I have been getting some compilation problems with latest master and needed to go back some commits... just to find this same issue! O_O I've gone down to previous ones (up to dda61c4 "x86 64 bits support") The worst thing is that I'm running Linux natively and they are some commits that I compiled from scratch. I've also checked about some installed package like QEmu or Linux kernel, but they are from several days before... Removing ```-enable-kvm``` doesn't help :-/

Don't know what's happening here, but seems something serious and don't know what could be happening here... :-(

**Comment by piranna** [comment]
Ok, I think I've found it! :-D Last Tuesday [Node.js got updated to v0.11.15](http://blog.nodejs.org/2015/01/20/node-v0-11-15-unstable/). Since we are using [the latest available unstable release](https://github.com/NodeOS/NodeOS/blob/6d6cbf38f8e2c43500d231dff98065fa142d26d4/node_modules/nodeos-barebones/scripts/preinstall#L9), I've hardcoded it to use the v0.11.14 version and has been able to run it :-) Need to test with a fully clean repo, but seems that's the reason why it didn't worked. @joeking11829, could you be able to confirm this? If so, then maybe we should use fixed versions instead of depend in the latest ones available, and maybe configure a bot task to test the new ones, what do you think?

**Comment by piranna** [comment]
[I've open an issue on Node.js](https://github.com/joyent/node/issues/9097) regarding to this regression.

**Comment by joeking11829** [comment]
Hi

I download the new repo for NodeOS.
And it works.
I can launch NodeOS on QEMU simulator.

But I get another error.

Error log:

[   14.856312] EXT4-fs (sda): couldn't mount as ext3 due to feature incompatibilities
[   14.989441] EXT4-fs (sda): mounting ext2 file system using the ext4 subsystem
[   15.012137] EXT4-fs (sda): warning: mounting unchecked fs, running e2fsck is recommended
[   15.022995] EXT4-fs (sda): mounted filesystem without journal. Opts: errors=remount-ro
Error re-mounting / as read-only
[   15.861363] random: init urandom read with 87 bits of entropy available
[   21.733031] random: nonblocking pool is initialized
[   21.988577] EXT4-fs (sdb): couldn't mount as ext3 due to feature incompatibilities
[   22.005963] EXT4-fs (sdb): mounting ext2 file system using the ext4 subsystem
[   22.022120] EXT4-fs (sdb): warning: mounting unchecked fs, running e2fsck is recommended
[   22.027147] EXT4-fs (sdb): mounted filesystem without journal. Opts: 
fs.js:552
//  fs.writeSync(fd, buffer, offset, length[, position]);
                                ^
Error: ENOSPC, no space left on device '/root/.forever/n71b.log'
    at Error (native)
    at Object.fs.openSync (fs.js:455:18)
    at Object.forever.startDaemon (/root/lib/node_modules/forever/lib/forever.js:409:14)
    at /root/lib/node_modules/forever/bin/starter:50:13
    at Array.forEach (native)
    at Object.<anonymous> (/root/lib/node_modules/forever/bin/starter:30:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bin/users-services
fs.js:552
//  fs.writeSync(fd, buffer, offset, length[, position]);
                                ^
Error: ENOSPC, no space left on device '/root/.forever/cANd.log'
    at Error (native)
    at Object.fs.openSync (fs.js:455:18)
    at Object.forever.startDaemon (/root/lib/node_modules/forever/lib/forever.js:409:14)
    at /root/lib/node_modules/forever/lib/forever/cli.js:264:13
    at /root/lib/node_modules/forever/lib/forever/cli.js:150:5
    at /root/lib/node_modules/forever/lib/forever.js:352:11
    at Object.oncomplete (fs.js:93:15)




it look like mount root file system failed.

Any idea !?

**Comment by piranna** [comment]
> fs.js:552
> // fs.writeSync(fd, buffer, offset, length[, position]);
> ^
> Error: ENOSPC, no space left on device '/root/.forever/cANd.log'
> at Error (native)
> at Object.fs.openSync (fs.js:455:18)
> at Object.forever.startDaemon (/root/lib/node_modules/forever/lib/forever.js:409:14)
> at /root/lib/node_modules/forever/lib/forever/cli.js:264:13
> at /root/lib/node_modules/forever/lib/forever/cli.js:150:5
> at /root/lib/node_modules/forever/lib/forever.js:352:11
> at Object.oncomplete (fs.js:93:15)
>
> it look like mount root file system failed.
>
> Any idea !?

Oh, sh*t, my fault. No, both rootfs & usersfs has been mounted (good!
:-D ), but rootfs has filled. Yesterday while trying to make bootable
disk images I've also added a way so it's size is autocalculated (it
was hardcoded to 32MB before), seems we should not use it until we can
be sure rootfs will be read-only. Change this line

https://github.com/NodeOS/NodeOS/blob/cc343181619576fec9105900229f3b178c328000/node_modules/nodeos-rootfs/scripts/install#L89

as set this for the size instead

```bash
DISK_SIZE=32 # Size in MB
$((DISK_SIZE*1024))
```

I'll try to fix it later.


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
Fixed in master

**Comment by joeking11829** [comment]
Awesome !!

It works !!

**Comment by piranna** [comment]
I'm happy you got it working again :-)

**Comment by netlovers** [comment]
I just built the latest master and this error still shows up:
```
[   16.885384] EXT4-fs (sda): couldn't mount as ext3 due to feature incompatibilities
[   16.911772] EXT4-fs (sda): mounting ext2 file system using the ext4 subsystem
[   16.942064] EXT4-fs warning (device sda): ext4_update_dynamic_rev:698: updating to rev 1 because of new feature flag, running e2fsck is recommended
[   16.955621] EXT4-fs (sda): mounted filesystem without journal. Opts: errors=remount-ro
Error re-mounting / as read-only
```
And the system is quite slow to boot. I don't remember seeing these warnings the last time I built it.

**Comment by piranna** [comment]
Those errors are normal, it's only saying that the root filesystem is Ext4 but it's mounting it as Ext2, probably related to the auto filesystem detection (I don't know why, the order in ```/proc/filesystems``` that's used as basis is Ext3 Ext2 Ext4 while Ext4 should be the first one since it's the more feature complete...), and the last one is regarding to trying to remount the initramfs as read-only, that seems it's not possible by definition. When we move /root to the usersfs and upgrade to use Linux kernel 3.19 with multilayer read-only OverlayFS we'll make it read-only from start, so this will not be needed anymore. I wouldn't worry about any of the both problems :-)

Regarding to being slower, how much slower? It should fully boot in under 10 seconds... Do you have KVM disabled on QEmu? This would make it to boot up to 30 seconds...

**Comment by netlovers** [comment]
Yes, KVM is disabled, but it was not this slow the last time. It boots up around 20+ seconds, and the most wait time is when the mount warnings show up, so I guess they are related.

**Comment by piranna** [comment]
auto filesystem detection is implemented by reading ```/proc/filesystem``` and trying to mount the partition checking each of the partitions in order, so yes, they could be related since there's some IO sync things (do you remember the sync mount functions? ;-) ). Standard auto filesystem in the ```mount``` command do it in the same way.

**Comment by netlovers** [comment]
Yeah, I remember. However my main concern is that we didn't come a long way since I converted the old modules, and the boot time is already about 10 seconds slower. By the way the login is slow too. When I give it the password and press enter several seconds pass until it actually logs in.

**Comment by piranna** [comment]
I don't remember about having any similar issue, but it's true I'm having a hard time and didn't work on NodeOS since a week ago. I'll try to find some time and test it again paying attention to this.

**Comment by saurabhghewari** [comment]
I m installing NodeOS on Ubuntu 14.04LTS 32-bit.
I m Getting this error:-
configure: error: cannot run /bin/bash /home/saurabh/Downloads/NodeOS-master/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/deps/gcc/config.sub
Error compiling '/home/saurabh/Downloads/NodeOS-master/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/obj/i686/gcc'

npm ERR! Linux 3.13.0-35-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE
npm ERR! nodeos-cross-toolchain@0.0.0 install: `scripts/install`
npm ERR! Exit status 31
npm ERR! 
npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 install script 'scripts/install'.
npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-cross-toolchain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saurabh/Downloads/NodeOS-master/npm-debug.log

Help me!!!

**Comment by mcsosa121** [comment]
Did you try installing it using docker?

**Comment by saurabhghewari** [comment]
No, I have problem regarding the docker, in fact i didnt get through docker. So i tried Qemu.

**Comment by piranna** [comment]
Docker is currently unmaintained, hope we can retake it soon when finish to define the filesystem architecture.
